spring.application.name=catalog-service
server.port=8081
server.shutdown=graceful

# Expose all endpoints of Spring Boot Actuator
management.endpoints.web.exposure.include=*

spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/catalogdb}
spring.datasource.username=${DB_USERNAME:catalog}
spring.datasource.password=${DB_PASSWORD:catalog}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
catalog.page-size=10
